# Generated by Django 3.1.7 on 2021-04-10 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamifi', '0003_auto_20210404_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Running', 'RUNNING'), ('Swimming', 'SWIMMING'), ('Push-Ups', 'PUSH-UPS'), ('Weight Lifting', 'WEIGHT LIFTING'), ('Stretches', 'STRETCHES'), ('Yoga', 'YOGA')], max_length=50)),
                ('category', models.CharField(choices=[('Cardio', 'CARDIO'), ('Strength Training', 'STRENGTH TRAINING'), ('Flexibility Training', 'FLEXIBILITY TRAINING')], max_length=50)),
                ('finished', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
