# Generated by Django 3.1.7 on 2021-04-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamifi', '0004_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exp',
            field=models.IntegerField(default=100),
        ),
    ]
