# Generated by Django 3.1.7 on 2021-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamifi', '0008_auto_20210412_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobicexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flexibilityexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
