# Generated by Django 3.1.7 on 2021-04-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamifi', '0016_auto_20210418_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('2 Handed Kettlebell Swing', '2 Handed Kettlebell Swing'), ('Abduktoren-Maschine', 'Abduktoren-Maschine'), ('Adduktoren Maschine', 'Adduktoren Maschine'), ('Arnold Press', 'Arnold Press'), ('Arnold Shoulder Press', 'Arnold Shoulder Press'), ('Asai Squad', 'Asai Squad'), ('Ausfallschritte im Gehen', 'Ausfallschritte im Gehen'), ('Ausfallschritte Stehend', 'Ausfallschritte Stehend'), ('Ausfallschritt Trizepsdrücken ü. Kopf, ß-Stange', 'Ausfallschritt Trizepsdrücken ü. Kopf, ß-Stange'), ('Axe Hold', 'Axe Hold'), ('Axe Hold', 'Axe Hold'), ('Back Squat', 'Back Squat'), ('Bankdrücken Eng', 'Bankdrücken Eng'), ('Bankdrücken KH', 'Bankdrücken KH'), ('Bankdrücken LH', 'Bankdrücken LH'), ('Barbell Ab Rollout', 'Barbell Ab Rollout'), ('Barbell Hack Squats', 'Barbell Hack Squats'), ('Barbell Lunges', 'Barbell Lunges'), ('Barbell Reverse Wrist Curl', 'Barbell Reverse Wrist Curl'), ('Barbell Triceps Extension', 'Barbell Triceps Extension')], max_length=50),
        ),
    ]
