# Generated by Django 3.1.7 on 2021-04-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamifi', '0017_auto_20210419_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Abs', 'Abs'), ('Arms', 'Arms'), ('Back', 'Back'), ('Calves', 'Calves'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=50),
        ),
    ]
